### ISSUE TITLE
GPVのデータ取得のコードを含めた、全体像の絵を作ってReadMeを更新

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/Battery-Control-by-Reinforcement-Learning#13]
### 追加したい機能
GPVのデータ取得のコードを含めた、全体像の絵を作ってReadMeを更新

### Issueが解決した時に期待される結果
Readmeの絵が更新される。すべてのコードを処理するmain.pyを絵の中に追記する。

### 実装の指針
- 絵を描く（手書きでもよいし、PPTでもよい）

### このIssueの必要性
- GPVのデータ取得コードをどのように動作させるのかを明らかにする必要がある

### Issue解決の期限
- 2023/3/14まで
- 学会発表のために

**Comment by Takuya510634** [comment]
作成終了、後日プルリク予定。

**Comment by daisukekodaira** [comment]
素晴らしい絵が追加された！
