### ISSUE TITLE
sklearnまわりでimportエラー発生

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/Battery-Control-by-Reinforcement-Learning#3]
## このIssueで解決したい問題点の内容
main.pyとprice_forecast.pyを実行するとimportエラーで結果が得られない
![DSC_2660](https://user-images.githubusercontent.com/43132698/209103959-bb0bca19-e3a9-4d0c-8be1-11555a77f118.JPG)

## Issueが解決した時に期待される結果
importエラーの発生がなくなる。

## このIssueの必要性
実行結果が得られないので改修必須。

## 解決方法の指針
sklearn以下の個別のパッケージを pip installで入れればいけそう。

## Issue解決の期限
特になし。

**Comment by Takuya510634** [comment]
pip install properscoring
pip install preprocessing

をターミナルから入力したらエラー解消しました
