### ISSUE TITLE
Dockerコンテナから外部ネットワークへ接続できるようにソースを書き換える

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/battery-control-by-reinforcement-learning#42]
### 追加したい機能
Dockerコンテナから外部ネットワークへ接続できるようにソースを書き換える

### Issueが解決した時に期待される結果
以下２つのコードで、GPVのデータを外部の公開サーバーからリアルタイムでダウンロードできるようになる。
- weather_data_bid.py  
- weather_data_realtime.py  

### 実装の指針
Docker runの設定を変えればいけそう。以下URLを参照。  
https://knowledge.sakura.ad.jp/23899/  

### このIssueの必要性
リアルタイムの動作確認を行うために必要。  

### Issue解決の期限
特になし

**Comment by daisukekodaira** [comment]
2023/06/27 なぜか新しいデータがダウンロードできたかもしれない（？）

**Comment by Takuya510634** [comment]
なぜかできるようになっていた。
おそらくDocker構成変更の副次的効果

#44 にて機能を実装
