### ISSUE TITLE
weather_data_bid.csvの月の形式を変更

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/battery-control-by-reinforcement-learning#45]
## このIssueで解決したい問題点の内容
Actions -> workflow のTest Weather Data Bidで発生する以下のエラーの解決
具体的には、[weather_data_bid.py](https://github.com/daisukekodaira/battery-control-by-reinforcement-learning/blob/master/Battery-Control-By-Reinforcement-Learning/weather_data_bid.py)で出力されるcsvの日付がyyyy-m-dd方式である
![Capture](https://github.com/daisukekodaira/battery-control-by-reinforcement-learning/assets/43132698/e7698590-46af-46ed-89b5-fa5ba6818115)

```
==================================== ERRORS ====================================
___________ ERROR collecting tests/test_datetime_dayAfterTomorrow.py ___________
tests/test_datetime_dayAfterTomorrow.py:26: in <module>
    assert weather_data['date'].unique()[0] == tomorrow_str, f"Date {weather_data['date'].unique()[0]} in CSV is not tomorrow: {tomorrow_str}"
E   AssertionError: Date 2023-6-28 in CSV is not tomorrow: 2023-06-28
E   assert '2023-6-28' == '2023-06-28'
```

## Issueが解決した時に期待される結果
出力csvの日付の形式がyyyy-mm-ddになり、Actionsで緑✔がつく

## 実装の指針
- まかせる～

## このIssueの必要性
- 大した変更ではないが、練習のため（なので優先度は高くないです）
- Actionsを緑にすることの練習

## Issue解決の期限
とくになし！

## 関連する疑問点
- yyyy-m-dd形式とyyyy-mm-dd形式が混ざると良くない気がするが、実際は混ざったほうが都合がよい？

**Comment by Takuya510634** [comment]
- yyyy-mm-dd形式すること自体は可能
- 出力後、予測や充放電計画策定ではこれらを数値として処理する

->この機能の必要性は薄いと考えられます

**Comment by daisukekodaira** [comment]
後藤さんの言う通り必要ないのでcloseします
