### ISSUE TITLE
電力価格予測のグラフ描写

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/Battery-Control-by-Reinforcement-Learning#5]
### 追加したい機能
**price_forecast.py**の結果をグラフで確認できるようにする

### Issueが解決した時に期待される結果
グラフがpdfで保存される、またはwindowがでる

### 実装の指針
**ESS control.py**の中でグラフをpdfに保存しているので、そこのコードを真似すれば良さそう。

### このIssueの必要性
予測結果を定性的に判断できるようにするため。

### Issue解決の期限
特になし

**Comment by Takuya510634** [comment]
#16
