### ISSUE TITLE
PVからの直接売電をrewardに組み込む

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/battery-control-by-reinforcement-learning#54]
## 追加したい機能
- PVから系統へ直接売電する場合があるが、その際の収益がrewardに入るように変更する。

## Issueが解決した時に期待される結果
- PVから系統へ売電する分も含めて最適な充放電スケジュールが強化学習によって実現される。

## 実装の指針
- ESS_schedule.pyのdef reward_set(self, ACTION, n_battery)に実装する。（添付参照）
![Capture](https://github.com/daisukekodaira/battery-control-by-reinforcement-learning/assets/43132698/f1c68cba-7e06-4e51-994e-4bbbb0d51c73)

## このIssueの必要性
- 実際のユーザーが得られる利益を計算するため。蓄電池を利用することでによる利益を大きくできる。

## Issue解決の期限
- 2022/8/11まで

**Comment by daisukekodaira** [comment]
これ実装したけど学習が進むと何も動かなくなるんだっけ？

**Comment by Takuya510634** [comment]
売電にrewardを与えると、望ましくない挙動をした際のpenaltyを打ち消されます。
”蓄電池を動かすとpenaltyを受ける -> 何もせず売るのが最適解と学習”

となります。放電のみにrewardを与えるとほとんどがpenaltyなので、penaltyを受けない動作を身につけます。
