### ISSUE TITLE
inputdata.csvの作成

### ISSUE THREAD

**Issue by Takuya510634** [daisukekodaira/Battery-Control-by-Reinforcement-Learning#8]
### 追加したい機能
- PV予測、電力価格予測両方で使用するcsvファイルの作成

### Issueが解決した時に期待される結果
- 時系列の揃った予測データを作成することが出来る

### 実装の指針
- 現状必要なのは同じ時系列の「気象データ・発電量・電力価格」の3つ
- GPVや産総研データ、JEPXデータを使う？
- 気象データは高層気象台の観測データを編集して予測データに合わせてパラメータを更新

### このIssueの必要性
- 同じ時系列データが今後必要になってくる

### Issue解決の期限
- 5月初旬

**Comment by daisukekodaira** [comment]
3/1に話してもらった内容を追記して、期限を決めてください。
